---
title: "Takım: Team A"
sidebar: false 
---

MUY660-İş Analitiği dersi takım sayfamıza hoş geldiniz.

Bu analitik çalışmalarımızı paylaşıyoruz.

Lütfen faaliyetlerimizi görmek için için bizi takipte kalın.

## Takım Üyeleri

1.  [Mirac Göktuğ EKİCİ](/takim/goktug.qmd)

2.  [Yağız Eren UÇ](/takim/yagiz.qmd)

3.  [Emre Raşit EYİGÜN](/takim/emre.qmd)

4.  [Erdem AKSOY](/takim/Erdem_aksoy.qmd)

5.  [İlhan TEMİZ](/takim/ilhan.qmd)

6.  [Taha TARHAN](/takim/taha.qmd)

## Proje Adı

İnsanların Mutluluk Kaynakları Ve Oranları

## Proje Konusu

Bu projede MUY665-İş Analitiği ders içeriğinin analitik yaklaşımlarla iyileştirilmesini hedefledik. Analiz için veri görselleştirme yöntemleri kullanarak, veriler üzerine çalışmalar yaptık. Sonuç olarak, MUY660-İş Analitiği dersinin dünyadaki tüm derslerden daha iyi olduğunu ve bu dersi aldığımız için çok mutlu olduğumuzu tespit ettik. :)

## Veri Seti Hakkında Özet Bilgi

Bu proje, yıllar 2013'ten 2023'e kadar olan mutluluk oranlarını çeşitli kategorilere göre analiz etmeyi ve önümüzdeki yıllar için tahminler yapmayı amaçlamaktadır. Çalışmanın temel amacı, toplumun genel mutluluk seviyesini etkileyen faktörleri anlamak ve gelecekteki trendleri öngörmektir.

## Sonuçlar

Analiz sonuçlarına göre, mutluluk skorlarındaki değişimler ve bu değişimlerin potansiyel nedenleri tartışılmıştır. Ayrıca, 2024 yılı için yapılan tahminler paylaşılmıştır.
